server:
  port: 8011

logging:
  level:
    root: INFO

kafka.servers: localhost:9092
kafka.consumer.group-id: test
kafka.topic: test

tablemapping:
  table:
    orgName: SKCPDBA.KAFKA_TEST_1
    targetName: MPDB.KAFKA_TEST_TARGET

  columns:
    ID: target_ID
    CH: target_CH
    DTTM: target_DTTM


